import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Contactsbanner from "./components/Contactsbanner";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import Script from 'next/script';
import Header from "./Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Station",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}){
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }  
  return (
    <html lang="en">
      <NextIntlClientProvider>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <Header />


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}

      >
         

        <Image src={"https://res.cloudinary.com/dxvnon94f/image/upload/v1756182029/logo.png"} alt="logo" width={500} height={500} style={{position:"fixed",marginLeft:-20,top:0,left:0,backgroundColor:"transparent",zIndex:500,width:"12rem",height:"3rem"}} />
        <div style={{position:"fixed",bottom:15,left:15,zIndex:500}}>
          <Contactsbanner />
        </div>
        <SpeedInsights />
        <Analytics />
              <Script
        strategy="afterInteractive"
        src="https://www.googletagmanager.com/gtag/js?id=123"
      />
        {children}
       
      </body>
       </NextIntlClientProvider>
    </html>
  );
}
