import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Contactsbanner from "./components/Contactsbanner";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Station",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}){
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }  
  return (
    <html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}

      >
         <NextIntlClientProvider>
        <Image src={"/logo.png"} alt="logo" width={500} height={500} style={{position:"fixed",marginLeft:-20,top:0,left:0,backgroundColor:"transparent",zIndex:500,width:"12rem",height:"3rem"}} />
        <div style={{position:"fixed",bottom:15,left:15,zIndex:500}}>
          <Contactsbanner />
        </div>
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
